### PR TITLE
Fix #46 - MessageOptions tweaks to style(s)

### LINKED ISSUE #46: [Feature request/Bug] No way to control padding added when Avatar is disabled
**Is your feature request related to a problem? Please describe.**

When `showCurrentUserAvatar` is `false`  in `MessageOptions` you have no way to control the [padding that gets added](https://github.com/molteo-engineering-team/Dash-Chat-2/blob/main/lib/src/widgets/message_row/message_row.dart#L149-L155) (`10`). Our way around was to return a `SizedBox.shrink()` in the `avatarBuilder`. However, it looks like if `showCurrentUserAvatar` is set to `true` it will add a phantom avatar with the same `user.id` (not the other person id in the convo). This means that in our `avatarBuilder` we are not able to hide this avatar which exists in the stack but it set to a `opacity` of `0`.

**Describe the solution you'd like**

A way to control the padding or not add a phantom avatar. Example 3 gets us close to being able to do what we want. But there is a nagging overflow issue because the phantom avatar exists in the stack.

**Example 1 - in avatar builder returning `SizedBox.shrink()` for current user + `showCurrentUserAvatar: false`**
https://user-images.githubusercontent.com/825344/236341244-c0d4eb57-1f4a-45c4-a1ed-0c7ce86cb02b.png

**Example 2 - in avatar builder returning avatar for both +  `showCurrentUserAvatar: true`**
https://user-images.githubusercontent.com/825344/236341213-cc8870a1-ad4a-4638-a769-aaf3aad89e12.png

**Example 3 - in avatar builder returning `SizedBox.shrink()` for current user + `showCurrentUserAvatar: true`**
https://user-images.githubusercontent.com/825344/236341684-4b86eea8-d234-499f-843e-2f3c52d777b5.png

### PR DESCRIPTION
**Pull request by LegendAF**
We ran into some issues controlling some of the styles. I think this cleans up the Message styles specifically. Let me know your thoughts. This would fix https://github.com/molteo-engineering-team/Dash-Chat-2/issues/46 for us.

**Changes:**
- [Added a page for showing off changing the styles.](https://user-images.githubusercontent.com/825344/236457566-217f1095-47b8-4e75-bd23-eecb9f7d464f.png)
- Extracted styles that were hard coded into `MessageOptions`.
  - Moved (most) defaults into the constructor...seems cleaner and easier to see what the defaults are when you hove on the class. It's still a `const` so I feel like this is a good approach.

**Changelog:**
* Added `borderRadius` message option
* Added `marginDifferentAuthor` message option
* Added `marginSameAuthor` message option
* Added `spaceWhenAvatarIsMissing` message option
* Added `timeFontSize` message option
* Added `timePadding` message option
* Added `timeTextColor` message option
* Added `currentUserTimeTextColor` message option

### CODE REVIEW

**Comment by SebastienBtr** [comment]
Hey, pretty good changes overall, thanks 🎉

Feedback:

* Can you remove your changes to the changelog and pub file version, I do that myself when I publish a new version. But you can copy the nice list that you did in the changelogs in the PR conversation so I can use it as inspiration for later 👌

* `currentUserContainerColor no longer uses the primary color.` I disagree with this change, it uses the primary color so that the chat looks good even with 0 customizations, and in most cases using the primary color for the chat bubble makes sense so that'd be one thing you don't have to change yourself. However I think `currentUserTextColor` should also use a Theme param to use the default text color on primary 

* `Time inside of chat bubble is not backwards compatible ... inherited textColor/currentUserTextColor` It is nice that now it will be possible to custom this color but I think it should be equal to `textColor` and `currentUserTextColor` by default

**Comment by LegendAF** [comment]
I don't really foresee someone dropping Dash Chat onto their project and not changing things like the styles. Especially since only one item is themed. But, it's not something I strongly feel to fight for as we just override everything ourselves using parameters and builders applying our styles directly from our custom theme with extended parameters. 

I am not sure what theme param should be applied to `currentUserTextColor`. There are a lot of text styles such as `Theme.of(context).textTheme.bodyMedium.color` It feels weird and arbitrary to apply these theme colors to things. Especially if we start having the time fallback to this, now that time color would look something like:
```
messageOptions.currentUserTextColor ?? messageOptions.currentUserTimeTextColor ?? Theme.of(context).textTheme.bodyMedium.color
```

For example, our bubble in our app is not using the material theme primary color and would be applied with:

```
FCThemeData.of(context).chatMessageStyle.colorOutgoing;
```

I agree time should probably fall back to what it was for backwards compatibility.

**Comment by SebastienBtr** [comment]
`now that time color would look something like:

messageOptions.currentUserTimeTextColor ?? messageOptions.currentUserTextColor ?? Theme.of(context).textTheme.b`

No, it would look like this:

**Comment by SebastienBtr** [comment]
> Updated to your suggestions @SebastienBtr
> 
> Also renamed
> 
> * `spaceWhenAvatarIsMissing` to `spaceWhenAvatarIsHidden` (if you have a better name I am all ears)
> * `timeSpacing` to `timePadding`

Yes it's better like that

**Comment by SebastienBtr** [comment]
`Especially if we start having the time fallback to this, now that time color would look something like: messageOptions.currentUserTimeTextColor ?? messageOptions.currentUserTextColor ?? Theme.of(context).textTheme.bodyMedium.color`

To avoid using those color conditions in multiple places in the code, we could instead add functions in `MessageOptions`, like that:

```
  Color getCurrentUserContainerColor(BuildContext context) {
    return currentUserContainerColor ?? Theme.of(context).primaryColor;
  }

  Color getCurrentUserTextColor(BuildContext context) {
    return currentUserTextColor ?? Theme.of(context).colorScheme.onPrimary; // need to check if that's the right theme value
  }

   Color getCurrentUserTimeTextColor(BuildContext context) {
    return currentUserTimeTextColor ?? getCurrentUserTextColor(context);
  }

   Color getTimeTextColor() {
    return timeTextColor ?? textColor;
  }
```

That'd make for instance, this code that you wrote:

```
messageOptions.messageTimeBuilder != null
              ? messageOptions.messageTimeBuilder!(message, isOwnMessage)
              : Padding(
                  padding: messageOptions.timePadding,
                  child: Text(
                    (messageOptions.timeFormat ?? intl.DateFormat('HH:mm'))
                        .format(message.createdAt),
                    style: TextStyle(
                      color: isOwnMessage
                          ? messageOptions.currentUserTimeTextColor ??
                              messageOptions.currentUserTextColor
                          : messageOptions.timeTextColor ??
                              messageOptions.textColor,
                      fontSize: messageOptions.timeFontSize,
                    ),
                  ),
                ),
```

Into that:

```
messageOptions.messageTimeBuilder != null
              ? messageOptions.messageTimeBuilder!(message, isOwnMessage)
              : Padding(
                  padding: messageOptions.timePadding,
                  child: Text(
                    (messageOptions.timeFormat ?? intl.DateFormat('HH:mm'))
                        .format(message.createdAt),
                    style: TextStyle(
                      color: isOwnMessage
                          ? messageOptions.getCurrentUserTimeTextColor(context)
                          : messageOptions.getTimeTextColor(),
                      fontSize: messageOptions.timeFontSize,
                    ),
                  ),
                ),
```

**Comment by LegendAF** [comment]
@SebastienBtr That's a solid idea. What do you think of my implementation? I initially used `get` in front of the variable names but it felt somehow bad that you could then reference the original and bypass the "getter". Is that something we would want? If not I think that it feels cleaner just using `currentUserContainerColor(context)`.

**Comment by SebastienBtr** [comment]
Looks good to me
Did you check if Theme.of(context).colorScheme.onPrimary was the right color to use? I can check later when running your branch otherwise

**Comment by LegendAF** [comment]
@SebastienBtr I am not 100% sure so if you could check that would be awesome!

**Comment by SebastienBtr** [comment]
@all-contributors please add @LegendAF for code

**Comment by SebastienBtr** [comment]
@all-contributors please add @LegendAF for code

**Pull request merged**
