### PR TITLE
feat: add maxWidth msg option

### PR DESCRIPTION
**Pull request by fufesou**
Signed-off-by: fufesou <shuanglongchen@yeah.net>

For some apps, chat window is a popup widget. It may be not suitable to use device's screen size. Instead user may want to set specified message max width, which is adapted to widget width.

### CODE REVIEW

**Review by SebastienBtr — CHANGES_REQUESTED** [review]
Hey, thanks for your contribution! I can definitely see how useful it can be!

The only changes necessary are:
* In `lib/src/models/message_options.dart` you don't need to init the param to `null`, it will already be null by default
* In `lib/src/widgets/message_row/message_row.dart` you don't need to add a `maxWidth` param because you can already get it from the `messageOptions` param

**Comment by fufesou** [comment]
> Hey, thanks for your contribution! I can definitely see how useful it can be!
> 
> The only changes necessary are:
> 
> * In `lib/src/models/message_options.dart` you don't need to init the param to `null`, it will already be null by default
> * In `lib/src/widgets/message_row/message_row.dart` you don't need to add a `maxWidth` param because you can already get it from the `messageOptions` param

Thanks for your careful review.

**Review by SebastienBtr — APPROVED** [review]
that's perfect

**Comment by SebastienBtr** [comment]
@all-contributors please add @fufesou for code

**Pull request merged**
